### ISSUE TITLE
Corrupt File Download

### ISSUE THREAD

**Issue by Kheldor182** [RequiDev/darkorbit-resource-downloader#2]
Downloading any swf file makes the file unusable and unopenable.

**Comment by RequiDev** [comment]
It doesn't download swf files. If you want swf files, you have to change resources_3d.xml to resources.xml

**Comment by Kheldor182** [comment]
i did. But all downloaded swf files are unopenable after downloading.
Same if you do it for the do_img resources: https://darkorbit-22.bpsecure.com/do_img/global/xml/resource_items.xml
You cannot open any picture.

**Comment by RequiDev** [comment]
Fixed in https://github.com/RequiDev/darkorbit-resource-downloader/commit/d2fff47ee89724046293618d038eb6d0622f5bfe

**Comment by Kheldor182** [comment]
Works perfect. Thank you Requi, for everything you did and do for the DO Community. Really appreciate that.

**Comment by Kheldor182** [comment]
i really thank you for what you do and what you did for the do community.
It looks like it tries to download it all at once. takes 3.5 seconds now to download all 2891 files. most of them are unopenable now cause theyre filesize is 0kb. seems like it doesnt wait for the data before file creating or something... not quite sure.

**Comment by RequiDev** [comment]
Fixed in https://github.com/RequiDev/darkorbit-resource-downloader/commit/23878dfa1643fc424679c1851250f74ba12c0a93
That was my bad not thinking about how async works again.

**Comment by RequiDev** [comment]
You might like this one too: https://github.com/RequiDev/darkorbit-resource-downloader/commit/ae1910ba56fa94e8b05b42d8e8fd4682b17ed690

**Comment by Kheldor182** [comment]
everything works perfect now. Again thank you very much. I think [ae1910b](https://github.com/RequiDev/darkorbit-resource-downloader/commit/ae1910ba56fa94e8b05b42d8e8fd4682b17ed690) is the final build of this now. theres nothing what you could improve as far as i think. Thank you very much for that great piece of work.
